### ISSUE TITLE
Minor Typo in Interactive Canvas Codelab

### ISSUE THREAD

**Issue by frunkad** [yoichiro/codelabs#10]
Hi Yoichiro, first of much thanks for this Codelabs, had been looking out for something similar for long. 

Didn't wanted to sound rude, there's a small typo in Interactive Canvas Codelab, it says **intens** instead of intents on the 6th page. (Line 445 of index.html)

Also, I didn't knew we could create our own Codelabs, thanks for that. 🤗

**Comment by yoichiro** [comment]
@frunkad Thank you for the reporting!
